-- Tablas:
--   PolizaUsuario
CREATE TABLE poliza_usuario (
  NOMBRE VARCHAR(25) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  DIRECCION VARCHAR(25) NOT NULL,
  REGISTRO_INICIO TIMESTAMP(12) GENERATED ALWAYS AS ROW BEGIN NOT NULL,
  REGISTRO_FIN TIMESTAMP(12) GENERATED ALWAYS AS ROW END NOT NULL,
  INICIO_POLIZA DATE NOT NULL,
  FIN_POLIZA DATE NOT NULL,
  COSTO_POLIZA DECIMAL(9,2),
  COBERTURA INT NOT NULL,
  ANO_VEHICULO INT NOT NULL,
  MODEL_VEHICULO VARCHAR(20) NOT NULL,
  MARCA_VEHICULO VARCHAR(20) NOT NULL,
  PRECIO_VEHICULO DECIMAL(6,2) NOT NULL,
  NUMERO_SERIE_VEIHCULO VARCHAR(20) NOT NULL
  trans_start TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID IMPLICITLY HIDDEN,
  period SYSTEM_time(REGISTRO_INICIO,REGISTRO_FIN)
  period SYSTEM_time(INICIO_POLIZA,FIN_POLIZA)
);

CREATE TABLE  poliza_usuario_sys_history LIKE poliza_usuario;
